version: "3"
services:
  node-red_server_1:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_1}
    ports:
      - "${PORT_1}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_1
    volumes:
      - volume_server_1:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_2:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_2}
    ports:
      - "${PORT_2}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_2
    volumes:
      - volume_server_2:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_3:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_3}
    ports:
      - "${PORT_3}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_3
    volumes:
      - volume_server_3:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_4:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_4}
    ports:
      - "${PORT_4}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_4
    volumes:
      - volume_server_4:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_5:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_5}
    ports:
      - "${PORT_5}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_5
    volumes:
      - volume_server_5:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_6:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_6}
    ports:
      - "${PORT_6}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_6
    volumes:
      - volume_server_6:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env

  node-red_server_7:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
      - NODE_RED_ADMIN_PW=${NODE_RED_PW_7}
    ports:
      - "${PORT_7}:1880"
    command:
      - "--settings"
      - "/settings/settings.js"
    networks:
      - network_server_7
    volumes:
      - volume_server_7:/data
      - ./settings/settings.js:/data/settings.js
    env_file:
      - .env
     
volumes:
  volume_server_1:
  volume_server_2:
  volume_server_3:
  volume_server_4:
  volume_server_5:
  volume_server_6:
  volume_server_7:
  
networks:
  network_server_1:
  network_server_2:
  network_server_3:
  network_server_4:
  network_server_5:
  network_server_6:
  network_server_7:
